services:
    frontend:
        build: 
            context: ./frontend
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
        ports:
            - 5173:5173
        command: sh -c "npm install && npm run host"

    backend:
        build: 
            context: ./backend
        volumes:
            - ./backend:/app
        ports:
            - 3000:3000
        command: sh -c "npm install && npm run backend"


