services:
    frontend:
        build: 
            context: ./frontend
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
        ports:
            - 5173:5173
        command: ["npm", "run", "dev"]

    backend:
        build: 
            context: ./backend
        volumes:
            - ./backend:/app
        ports:
            - 3000:3000
        command: ["npm", "run", "backend"]


